#!/usr/bin/env python3
"""
config_pares.py — Lista de pares para escanear
Pares BingX Perpetual Futures con buen volumen
"""

PARES_ACTIVOS = [
    "BTC-USDT", "ETH-USDT", "BNB-USDT", "SOL-USDT", "XRP-USDT",
    "ADA-USDT", "AVAX-USDT", "DOGE-USDT", "DOT-USDT", "MATIC-USDT",
    "LINK-USDT", "UNI-USDT", "ATOM-USDT", "LTC-USDT", "ETC-USDT",
    "BCH-USDT", "APT-USDT", "ARB-USDT", "OP-USDT", "SUI-USDT",
    "INJ-USDT", "TIA-USDT", "SEI-USDT", "BLUR-USDT", "PEPE-USDT",
    "WIF-USDT", "BONK-USDT", "JTO-USDT", "PYTH-USDT", "JUP-USDT",
    "FIL-USDT", "ICP-USDT", "HBAR-USDT", "VET-USDT", "NEAR-USDT",
    "ALGO-USDT", "EGLD-USDT", "XLM-USDT", "FTM-USDT", "SAND-USDT",
    "MANA-USDT", "AXS-USDT", "GALA-USDT", "ENJ-USDT", "CHZ-USDT",
    "FLOW-USDT", "ROSE-USDT", "ONE-USDT", "ZIL-USDT", "KAVA-USDT",
    "AAVE-USDT", "CRV-USDT", "MKR-USDT", "COMP-USDT", "SNX-USDT",
    "YFI-USDT", "SUSHI-USDT", "1INCH-USDT", "BAL-USDT", "REN-USDT",
    "LDO-USDT", "RPL-USDT", "FXS-USDT", "CVX-USDT", "FRAX-USDT",
    "GMX-USDT", "GNS-USDT", "DYDX-USDT", "PERP-USDT", "RLB-USDT",
    "STG-USDT", "MAGIC-USDT", "TRB-USDT", "LQTY-USDT", "VELA-USDT",
    "LEVER-USDT", "UNFI-USDT", "HOOK-USDT", "GLMR-USDT", "MOVR-USDT",
    "KSM-USDT", "PARA-USDT", "CFX-USDT", "ACH-USDT", "CELO-USDT",
    "BAND-USDT", "API3-USDT", "TRX-USDT", "EOS-USDT", "XTZ-USDT",
    "ZEC-USDT", "DASH-USDT", "XMR-USDT", "NEO-USDT", "WAVES-USDT",
    "ICX-USDT", "ONT-USDT", "QTUM-USDT", "ZRX-USDT", "BAT-USDT",
    "GRT-USDT", "SKL-USDT", "NMR-USDT", "OCEAN-USDT", "FET-USDT",
    "AGIX-USDT", "RNDR-USDT", "THETA-USDT", "TFUEL-USDT", "HOT-USDT",
    "VRA-USDT", "WIN-USDT", "FLOKI-USDT", "SHIB-USDT", "LUNC-USDT",
    "LUNA-USDT", "USTC-USDT", "PEOPLE-USDT", "NYM-USDT", "ORCA-USDT",
    "RAY-USDT", "MNGO-USDT", "COPE-USDT", "STEP-USDT", "MEDIA-USDT",
    "AUDIO-USDT", "ALICE-USDT", "TLM-USDT", "HERO-USDT", "CHESS-USDT",
    "DUSK-USDT", "SXP-USDT", "XVS-USDT", "BAKE-USDT", "BURGER-USDT",
    "CAKE-USDT", "AUTO-USDT", "ALPHA-USDT", "BELT-USDT", "WATCH-USDT",
    "POLS-USDT", "HARD-USDT", "FARM-USDT", "CREAM-USDT", "BADGER-USDT",
    "PICKLE-USDT", "YFII-USDT", "BTCST-USDT", "FOR-USDT", "COCOS-USDT",
    "REEF-USDT", "BEL-USDT", "WING-USDT", "HELMET-USDT", "BFT-USDT",
    "MBOX-USDT", "NFT-USDT", "REVV-USDT", "NAOS-USDT", "ORBS-USDT",
    "TORN-USDT", "FIDA-USDT", "KIN-USDT", "MAPS-USDT", "OXY-USDT",
    "STMX-USDT", "COS-USDT", "DOCK-USDT", "PERL-USDT", "SPARTA-USDT",
    "VITE-USDT", "WAN-USDT", "FUN-USDT", "CTSI-USDT", "ARPA-USDT",
    "TROY-USDT", "WRX-USDT", "LOOM-USDT", "NULS-USDT", "ANKR-USDT",
    "IOST-USDT", "CELR-USDT", "DENT-USDT", "MITH-USDT", "QKC-USDT",
    "IRIS-USDT", "TCT-USDT", "OGN-USDT", "LRC-USDT", "MDT-USDT",
    "MBL-USDT", "STORJ-USDT", "STPT-USDT", "GTO-USDT", "BLZ-USDT",
    "MCO-USDT", "IDEX-USDT", "DREP-USDT", "TOMO-USDT", "TFUEL-USDT",
    "IOTA-USDT", "LSK-USDT", "SC-USDT", "NANO-USDT", "XEM-USDT",
    "STEEM-USDT", "SRM-USDT", "STEP-USDT", "BIT-USDT", "PROM-USDT",
    "AKRO-USDT", "FORTH-USDT", "BOND-USDT", "XVG-USDT", "STRAX-USDT",
    "KMD-USDT", "PIVX-USDT", "NXS-USDT", "PART-USDT", "NAV-USDT",
    "FLUX-USDT", "RVN-USDT", "HNT-USDT", "MOBILE-USDT", "IOT-USDT",
    "C98-USDT", "JASMY-USDT", "AMP-USDT", "SLP-USDT", "PLA-USDT",
    "IDEX-USDT", "DODO-USDT", "QUICK-USDT", "MASK-USDT", "TORN-USDT",
    "RIF-USDT", "TELOS-USDT", "LYRA-USDT", "PAXG-USDT", "OMG-USDT",
    "POWR-USDT", "QNT-USDT", "CEEK-USDT", "VTHO-USDT", "RUNE-USDT",
    "PENDLE-USDT", "RDNT-USDT", "WLD-USDT", "CYBER-USDT", "ARK-USDT",
    "MEME-USDT", "ORDI-USDT", "SATS-USDT", "RATS-USDT", "1000SATS-USDT",
    "ACE-USDT", "NFP-USDT", "AI-USDT", "XAI-USDT", "MANTA-USDT",
    "ALT-USDT", "PIXEL-USDT", "STRK-USDT", "DYM-USDT", "PORTAL-USDT",
    "AEVO-USDT", "ETHFI-USDT", "ENA-USDT", "WBTC-USDT", "W-USDT",
    "OMNI-USDT", "REZ-USDT", "BB-USDT", "NOT-USDT", "IO-USDT",
    "ZK-USDT", "LISTA-USDT", "ZRO-USDT", "BLAST-USDT", "BOME-USDT",
    "DOGS-USDT", "HMSTR-USDT", "CATI-USDT", "EIGEN-USDT", "SCR-USDT",
    "NEIRO-USDT", "1000NEIRO-USDT", "GOAT-USDT", "MOODENG-USDT",
    "MEW-USDT", "PNUT-USDT", "ACT-USDT", "CHILLGUY-USDT", "MOVE-USDT",
    "ME-USDT", "PENGU-USDT", "USUAL-USDT", "VIRTUAL-USDT", "THE-USDT",
    "MORPHO-USDT", "HYPE-USDT", "KAIA-USDT", "BERA-USDT", "IP-USDT",
    "TST-USDT", "LAYER-USDT", "B2-USDT", "BIO-USDT", "ONDO-USDT",
    "TRUMP-USDT", "MELANIA-USDT", "FARTCOIN-USDT", "AI16Z-USDT",
    "GRIFFAIN-USDT", "ZEREBRO-USDT", "SWARMS-USDT", "AIXBT-USDT",
]


def get_pares_por_prioridad() -> list:
    """Retorna pares ordenados por prioridad (mayor volumen primero)"""
    # Los primeros pares tienen mayor volumen y liquidez
    prioridad_alta = PARES_ACTIVOS[:30]
    resto = PARES_ACTIVOS[30:]
    return prioridad_alta + resto


def get_pares_count() -> int:
    return len(PARES_ACTIVOS)
